# Home Assistant configuration.yaml with MQTT camera setup for King Kiosk

# Configure MQTT integration
mqtt:
  broker: mqtt-broker # Use service name from docker-compose
  port: 1883
  discovery: true
  discovery_prefix: homeassistant

# Example camera configuration if auto-discovery doesn't work
camera:
  - platform: mqtt
    name: "King Kiosk Screenshot"
    topic: "kingkiosk/device-12345/screenshot" # Replace with your device name
    
# Example automation to take a screenshot every hour
automation:
  - alias: "Take hourly kiosk screenshot"
    trigger:
      - platform: time_pattern
        minutes: "0"  # Every hour at :00 minutes
    action:
      - service: mqtt.publish
        data:
          topic: "kiosk/device-12345/command"  # Replace with your device name
          payload: '{"command": "screenshot"}'
          
  - alias: "Take screenshot on motion detection"
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor
        to: "on"
    action:
      - service: mqtt.publish
        data:
          topic: "kiosk/device-12345/command"
          payload: '{"command": "screenshot"}'
      - delay: '00:00:05'  # Wait 5 seconds for screenshot to process
      - service: notify.mobile_app
        data:
          title: "Motion Detected"
          message: "Motion was detected. A screenshot has been taken."
          data:
            image: "{{ states.camera.king_kiosk_screenshot.attributes.entity_picture }}"
